use engine_platform::{AtomicFileService, AtomicWriteError, AtomicWriteOptions};
use std::fs;
use std::path::{Path, PathBuf};
use thiserror::Error;

const GENERATED_MARKER: &str = "Generated by Rustic Game Engine. Safe to regenerate.";

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WorkspaceGeneration {
    pub workspace_file: PathBuf,
    pub generated_files: Vec<PathBuf>,
    pub preserved_user_files: Vec<PathBuf>,
    pub agent_integration_files: Vec<PathBuf>,
}

#[derive(Debug, Error)]
pub enum WorkspaceError {
    #[error("workspace I/O failed at {path}: {source}")]
    Io {
        path: PathBuf,
        #[source]
        source: std::io::Error,
    },
    #[error("transactional workspace write failed: {0}")]
    Write(#[from] AtomicWriteError),
}

/// Generates reproducible VS Code metadata and EmmyLua-compatible API stubs.
/// User-owned `.vscode/settings.json` and existing non-generated files are untouched.
/// Generates reproducible metadata while preserving user-owned editor files.
///
/// # Errors
/// Returns an error when directories or transactional files cannot be created.
pub fn generate_programming_workspace(
    project_root: &Path,
    project_name: &str,
) -> Result<WorkspaceGeneration, WorkspaceError> {
    let generated = project_root.join(".rustic/generated/programming");
    fs::create_dir_all(&generated).map_err(|source| WorkspaceError::Io {
        path: generated.clone(),
        source,
    })?;
    let files = AtomicFileService::new();
    let workspace_file = project_root.join(format!("{project_name}.code-workspace"));
    let workspace = format!(
        "{{\n  \"//\": \"{GENERATED_MARKER}\",\n  \"folders\": [{{ \"path\": \".\" }}],\n  \"settings\": {{\n    \"Lua.workspace.library\": [\".rustic/generated/programming\"],\n    \"C_Cpp.default.includePath\": [\"${{workspaceFolder}}/.rustic/generated/programming\"]\n  }}\n}}\n"
    );
    write_generated_or_preserve(&files, &workspace_file, workspace.as_bytes())?;
    let extensions = generated.join("extensions.json");
    let extension_text = format!(
        "{{\n  \"//\": \"{GENERATED_MARKER}\",\n  \"recommendations\": [\"sumneko.lua\", \"dbaeumer.vscode-eslint\", \"ms-vscode.cpptools\"]\n}}\n"
    );
    files.write_with_options(
        &extensions,
        extension_text.as_bytes(),
        AtomicWriteOptions { keep_backup: false },
    )?;
    let api = generated.join("rustic_api.lua");
    let api_text = format!(
        "---@meta\n-- {GENERATED_MARKER}\n---@class RusticTransform\n---@field x number\n---@field y number\n---@field z number\n---@class RusticApi\n---@field entity_id fun(): string\n---@field delta_time fun(): number\n---@field fixed_delta_time fun(): number\n---@field get_translation fun(): number, number, number\n---@field set_translation fun(x:number,y:number,z:number)\n---@field find_entity fun(name_or_id:string): string|nil, string|nil\n---@field input fun(action:string): table\n---@field log fun(level:string,message:string,fields:table|nil)\n---@field get_property fun(name:string): any\n---@field set_property fun(name:string,value:any): boolean, string|nil\n---@field set_enabled fun(enabled:boolean)\n---@type RusticApi\nrustic = rustic\n---@class RusticInstanceApi\n---@field add fun(source:string,parent:string|nil): string\n---@field clone fun(source:string,parent:string|nil): string\n---@type RusticInstanceApi\ninstance = instance\n---@class RusticGameApi\n---@field setCurrentCamera fun(source:string|table)\n---@type RusticGameApi\nGame = Game\n"
    );
    files.write_with_options(
        &api,
        api_text.as_bytes(),
        AtomicWriteOptions { keep_backup: false },
    )?;
    let javascript_api = generated.join("rustic_api.d.ts");
    let javascript_api_text = format!(
        "// {GENERATED_MARKER}\ntype RusticActionState = Readonly<{{ pressed: boolean; released: boolean; held: boolean; axis: number }}>;\ninterface RusticApi {{\n  entity_id(): string;\n  delta_time(): number;\n  fixed_delta_time(): number;\n  get_translation(): [number, number, number];\n  set_translation(x: number, y: number, z: number): void;\n  input(action: string): RusticActionState;\n  log(level: string, message: string): void;\n  get_property(name: string): unknown;\n  set_property(name: string, value: unknown): void;\n  set_enabled(enabled: boolean): void;\n}}\ndeclare const Game: Readonly<{{ setCurrentCamera(source: string): void; scene: {{ Find(path: string): string | undefined; List(): string[] }} }}>;\ndeclare const rustic: Readonly<RusticApi>;\ndeclare const instance: Readonly<{{ add(source: string, parent?: string | null): void; clone(source: string, parent?: string | null): void }}>;\ndeclare interface RusticBehavior {{\n  on_create?(): void;\n  on_start?(): void;\n  fixed_update?(delta: number): void;\n  update?(delta: number): void;\n  on_destroy?(): void;\n  on_stop?(): void;\n}}\ndeclare var behavior: RusticBehavior;\n"
    );
    files.write_with_options(
        &javascript_api,
        javascript_api_text.as_bytes(),
        AtomicWriteOptions { keep_backup: false },
    )?;
    let cpp_api = generated.join("rustic.hpp");
    files.write_with_options(
        &cpp_api,
        crate::cpp_sdk::HEADER.as_bytes(),
        AtomicWriteOptions { keep_backup: false },
    )?;
    let protocol_schema = generated.join("rustic_host_protocol.schema.json");
    let protocol_schema_text = format!(
        "{{\n  \"$schema\": \"https://json-schema.org/draft/2020-12/schema\",\n  \"title\": \"Rustic gameplay host protocol\",\n  \"description\": \"{GENERATED_MARKER}\",\n  \"type\": \"object\",\n  \"required\": [\"format_version\", \"callback\", \"entity_id\", \"translation\", \"properties\"],\n  \"properties\": {{\n    \"format_version\": {{ \"const\": 1 }},\n    \"callback\": {{ \"enum\": [\"on_create\", \"on_start\", \"fixed_update\", \"update\", \"on_destroy\", \"on_stop\"] }},\n    \"delta\": {{ \"type\": [\"number\", \"null\"] }},\n    \"entity_id\": {{ \"type\": \"string\" }},\n    \"delta_time\": {{ \"type\": \"number\" }},\n    \"fixed_delta_time\": {{ \"type\": \"number\" }},\n    \"translation\": {{ \"type\": \"array\", \"minItems\": 3, \"maxItems\": 3, \"items\": {{ \"type\": \"number\" }} }},\n    \"properties\": {{ \"type\": \"object\" }},\n    \"attributes\": {{ \"type\": \"object\" }},\n    \"scene_paths\": {{ \"type\": \"object\" }},\n    \"actions\": {{ \"type\": \"object\" }},\n    \"keys\": {{ \"type\": \"object\" }},\n    \"key_events\": {{ \"type\": \"array\" }},\n    \"any_key_pressed\": {{ \"type\": \"boolean\" }},\n    \"commands\": {{ \"description\": \"Responses may include set_translation, set_property, edit_attribute, log, set_enabled, add_instance, clone_instance, or set_current_camera (source: camera path or entity ID).\", \"type\": \"array\" }}\n  }}\n}}\n"
    );
    files.write_with_options(
        &protocol_schema,
        protocol_schema_text.as_bytes(),
        AtomicWriteOptions { keep_backup: false },
    )?;
    let agent_integration_files = generate_agent_integrations(project_root, project_name, &files)?;
    let preserved = [
        project_root.join(".vscode/settings.json"),
        project_root.join(".vscode/tasks.json"),
        project_root.join(".vscode/launch.json"),
    ]
    .into_iter()
    .filter(|p| p.exists())
    .collect();
    Ok(WorkspaceGeneration {
        workspace_file,
        generated_files: vec![extensions, api, javascript_api, cpp_api, protocol_schema],
        preserved_user_files: preserved,
        agent_integration_files,
    })
}

fn generate_agent_integrations(
    project_root: &Path,
    project_name: &str,
    files: &AtomicFileService,
) -> Result<Vec<PathBuf>, WorkspaceError> {
    let backend = std::env::current_exe()
        .ok()
        .and_then(|path| {
            path.parent()
                .map(|parent| parent.join("rustic-agent-backend"))
        })
        .filter(|path| {
            path.with_extension(std::env::consts::EXE_EXTENSION)
                .is_file()
        })
        .map(|path| path.with_extension(std::env::consts::EXE_EXTENSION))
        .unwrap_or_else(|| PathBuf::from("rustic-agent-backend"));
    let backend = backend.to_string_lossy();
    let root = project_root.to_string_lossy();
    let mcp = serde_json::to_vec_pretty(&serde_json::json!({
        "mcpServers": {"rustic-workspace": {"command": backend, "args": ["--project", root]}}
    }))
    .expect("agent MCP configuration is serializable");
    let codex_plugin = project_root.join(".agents/plugins/rustic-workspace");
    let codex_skill = codex_plugin.join("skills/rustic-workspace");
    let claude_skill = project_root.join(".claude/skills/rustic-workspace");
    for directory in [&codex_skill, &claude_skill] {
        fs::create_dir_all(directory).map_err(|source| WorkspaceError::Io {
            path: directory.to_path_buf(),
            source,
        })?;
    }
    let plugin_manifest = codex_plugin.join(".codex-plugin/plugin.json");
    fs::create_dir_all(plugin_manifest.parent().expect("manifest has parent")).map_err(
        |source| WorkspaceError::Io {
            path: plugin_manifest.clone(),
            source,
        },
    )?;
    let manifest = serde_json::to_vec_pretty(&serde_json::json!({
        "name":"rustic-workspace", "version": env!("CARGO_PKG_VERSION"),
        "description":"Control and inspect a Rustic Game Engine project", "skills":"./skills/",
        "mcpServers":"./.mcp.json", "author":{"name":"Rustic Game Engine Contributors"},
        "interface":{"displayName":"Rustic Workspace","shortDescription":"Inspect scenes and safely edit this Rustic project","longDescription":"Project-aware tools for workspace files, scene structure, and Rustic documentation.","developerName":"Rustic Game Engine Contributors","category":"Developer Tools","capabilities":["Interactive","Write"]}
    })).expect("plugin manifest is serializable");
    files.write_with_options(
        &plugin_manifest,
        &manifest,
        AtomicWriteOptions { keep_backup: false },
    )?;
    let skill = format!(
        r#"---
name: rustic-workspace
description: Work on the {project_name} Rustic Game Engine project; use when asked to inspect or change its workspace, scenes, scripts, assets, or project documentation.
---

# Rustic workspace

Use the `rustic-workspace` MCP tools before editing to confirm the project root and inspect the active scene. Read `AGENTS.md` or `CLAUDE.md` for repository routing. Use `scene_summary` rather than guessing the contents of a `.scene` file. Keep game code and content within this project unless the user explicitly asks to modify the engine source.
"#
    );
    let codex_skill_file = codex_skill.join("SKILL.md");
    let claude_skill_file = claude_skill.join("SKILL.md");
    files.write_with_options(
        &codex_skill_file,
        skill.as_bytes(),
        AtomicWriteOptions { keep_backup: false },
    )?;
    files.write_with_options(
        &claude_skill_file,
        skill.as_bytes(),
        AtomicWriteOptions { keep_backup: false },
    )?;
    let mcp_file = project_root.join(".mcp.json");
    files.write_with_options(&mcp_file, &mcp, AtomicWriteOptions { keep_backup: false })?;
    let plugin_mcp = codex_plugin.join(".mcp.json");
    files.write_with_options(&plugin_mcp, &mcp, AtomicWriteOptions { keep_backup: false })?;
    let marketplace_file = project_root.join(".agents/plugins/marketplace.json");
    let marketplace = serde_json::to_vec_pretty(&serde_json::json!({
        "name":"rustic-project", "interface":{"displayName":"Rustic Project"},
        "plugins":[{"name":"rustic-workspace","source":{"source":"local","path":"./rustic-workspace"},"policy":{"installation":"INSTALLED_BY_DEFAULT","authentication":"ON_INSTALL"},"category":"Developer Tools"}]
    })).expect("plugin marketplace is serializable");
    files.write_with_options(
        &marketplace_file,
        &marketplace,
        AtomicWriteOptions { keep_backup: false },
    )?;
    let instructions = format!(
        "# {project_name} agent workspace\n\nThis folder is a Rustic game project. Make gameplay, scene, asset, shader, material, prefab, plugin, and configuration changes inside this project root. Do not edit the Rustic engine source repository unless the user explicitly requests engine work. Use the `rustic-workspace` MCP server to inspect scenes and locate documentation.\n"
    );
    let agents = project_root.join("AGENTS.md");
    let claude = project_root.join("CLAUDE.md");
    write_generated_or_preserve(
        files,
        &agents,
        format!("<!-- {GENERATED_MARKER} -->\n{instructions}").as_bytes(),
    )?;
    write_generated_or_preserve(
        files,
        &claude,
        format!("<!-- {GENERATED_MARKER} -->\n{instructions}").as_bytes(),
    )?;
    Ok(vec![
        plugin_manifest,
        codex_skill_file,
        claude_skill_file,
        mcp_file,
        plugin_mcp,
        marketplace_file,
        agents,
        claude,
    ])
}

/// Installs the Rustic skill, Claude slash command, and Codex plugin for this user.
///
/// # Errors
/// Returns an error when the user profile or integration files cannot be updated.
pub fn install_user_agent_integrations() -> Result<(), WorkspaceError> {
    let backend = std::env::current_exe()
        .ok()
        .and_then(|path| {
            path.parent()
                .map(|parent| parent.join("rustic-agent-backend"))
        })
        .map(|path| path.with_extension(std::env::consts::EXE_EXTENSION))
        .filter(|path| path.is_file())
        .unwrap_or_else(|| PathBuf::from("rustic-agent-backend"));
    install_user_agent_integrations_at(&backend, &AtomicFileService::new())
}

fn install_user_agent_integrations_at(
    backend: &Path,
    files: &AtomicFileService,
) -> Result<(), WorkspaceError> {
    let home = std::env::var_os("USERPROFILE")
        .or_else(|| std::env::var_os("HOME"))
        .map(PathBuf::from)
        .ok_or_else(|| WorkspaceError::Io {
            path: PathBuf::from("user profile"),
            source: std::io::Error::new(
                std::io::ErrorKind::NotFound,
                "user profile is unavailable",
            ),
        })?;
    let skill = r#"---
name: rustic-workspace
description: Control and inspect the Rustic Game Engine project in the current workspace; use for Rustic scenes, scripts, assets, docs, or engine/project repository routing.
---

# Rustic workspace

Use the `rustic-workspace` MCP tools first to identify the active project root, inspect scenes, and locate engine documentation. Keep game content in the project reported by `workspace_info`. Only edit the engine source repository when the user explicitly requests engine changes. Use `scene_summary` before changing a scene rather than guessing its serialized structure.
"#;
    let codex_skill = home.join(".agents/skills/rustic-workspace");
    let claude_skill = home.join(".claude/skills/rustic-workspace");
    let claude_command = home.join(".claude/commands");
    let plugin = home.join(".agents/plugins/plugins/rustic-workspace");
    for directory in [
        &codex_skill,
        &claude_skill,
        &claude_command,
        &plugin.join("skills/rustic-workspace"),
        &plugin.join(".codex-plugin"),
    ] {
        fs::create_dir_all(directory).map_err(|source| WorkspaceError::Io {
            path: directory.to_path_buf(),
            source,
        })?;
    }
    files.write_with_options(
        &codex_skill.join("SKILL.md"),
        skill.as_bytes(),
        AtomicWriteOptions { keep_backup: false },
    )?;
    files.write_with_options(
        &claude_skill.join("SKILL.md"),
        skill.as_bytes(),
        AtomicWriteOptions { keep_backup: false },
    )?;
    files.write_with_options(
        &plugin.join("skills/rustic-workspace/SKILL.md"),
        skill.as_bytes(),
        AtomicWriteOptions { keep_backup: false },
    )?;
    let openai_yaml = "interface:\n  display_name: \"Rustic Workspace\"\n  short_description: \"Inspect and edit the active Rustic project\"\n  default_prompt: \"Use Rustic Workspace to inspect the current project and complete my request.\"\n";
    fs::create_dir_all(codex_skill.join("agents")).map_err(|source| WorkspaceError::Io {
        path: codex_skill.join("agents"),
        source,
    })?;
    files.write_with_options(
        &codex_skill.join("agents/openai.yaml"),
        openai_yaml.as_bytes(),
        AtomicWriteOptions { keep_backup: false },
    )?;
    let command = "Use the `rustic-workspace` MCP tools to identify and inspect the current Rustic project, read its agent instructions and relevant docs, inspect the active scene, then complete the user's request in the correct project or engine repository.\n";
    files.write_with_options(
        &claude_command.join("rustic-workspace.md"),
        command.as_bytes(),
        AtomicWriteOptions { keep_backup: false },
    )?;
    let command_text = backend.to_string_lossy();
    let mcp = serde_json::to_vec_pretty(
        &serde_json::json!({"mcpServers":{"rustic-workspace":{"command":command_text,"args":[]}}}),
    )
    .expect("MCP config serializes");
    files.write_with_options(
        &plugin.join("mcp.json"),
        &mcp,
        AtomicWriteOptions { keep_backup: false },
    )?;
    let portable = serde_json::to_vec_pretty(&serde_json::json!({
        "$schema":"https://agent-plugins.org/schemas/1.0.0/plugin.schema.json", "name":"rustic-workspace", "version":env!("CARGO_PKG_VERSION"),
        "description":"Control and inspect the active Rustic Game Engine workspace", "author":{"name":"Rustic Game Engine Contributors"}
    })).expect("portable plugin manifest serializes");
    files.write_with_options(
        &plugin.join("plugin.json"),
        &portable,
        AtomicWriteOptions { keep_backup: false },
    )?;
    let compat = serde_json::to_vec_pretty(&serde_json::json!({
        "name":"rustic-workspace", "version":env!("CARGO_PKG_VERSION"), "description":"Control and inspect the active Rustic Game Engine workspace",
        "author":{"name":"Rustic Game Engine Contributors"}, "skills":"./skills/", "mcpServers":"./mcp.json",
        "interface":{"displayName":"Rustic Workspace","shortDescription":"Inspect and edit the active Rustic project","longDescription":"Project-aware tools for workspace files, scene structure, and Rustic documentation.","developerName":"Rustic Game Engine Contributors","category":"Developer Tools","capabilities":["Interactive","Write"]}
    })).expect("compatibility plugin manifest serializes");
    files.write_with_options(
        &plugin.join(".codex-plugin/plugin.json"),
        &compat,
        AtomicWriteOptions { keep_backup: false },
    )?;
    update_codex_mcp(&home.join(".codex/config.toml"), backend, files)?;
    update_claude_mcp(&home.join(".claude.json"), backend, files)?;
    update_personal_marketplace(&home.join(".agents/plugins/marketplace.json"), files)?;
    Ok(())
}

fn update_codex_mcp(
    path: &Path,
    backend: &Path,
    files: &AtomicFileService,
) -> Result<(), WorkspaceError> {
    use toml_edit::{Array, DocumentMut, Item, Table, value};

    let text = if path.is_file() {
        fs::read_to_string(path).map_err(|source| WorkspaceError::Io {
            path: path.to_path_buf(),
            source,
        })?
    } else {
        String::new()
    };
    let mut document = text
        .parse::<DocumentMut>()
        .map_err(|error| WorkspaceError::Io {
            path: path.to_path_buf(),
            source: std::io::Error::new(std::io::ErrorKind::InvalidData, error),
        })?;
    if !document.contains_key("mcp_servers") {
        document["mcp_servers"] = Item::Table(Table::new());
    }
    let servers = document["mcp_servers"]
        .as_table_mut()
        .ok_or_else(|| WorkspaceError::Io {
            path: path.to_path_buf(),
            source: std::io::Error::new(
                std::io::ErrorKind::InvalidData,
                "Codex mcp_servers must be a TOML table",
            ),
        })?;
    let mut server = Table::new();
    server["command"] = value(backend.to_string_lossy().as_ref());
    server["args"] = value(Array::new());
    server["enabled"] = value(true);
    servers["rustic-workspace"] = Item::Table(server);
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|source| WorkspaceError::Io {
            path: parent.to_path_buf(),
            source,
        })?;
    }
    files.write_with_options(
        path,
        document.to_string().as_bytes(),
        AtomicWriteOptions { keep_backup: true },
    )?;
    Ok(())
}

fn update_claude_mcp(
    path: &Path,
    backend: &Path,
    files: &AtomicFileService,
) -> Result<(), WorkspaceError> {
    let mut value = if path.is_file() {
        let text = fs::read_to_string(path).map_err(|source| WorkspaceError::Io {
            path: path.to_path_buf(),
            source,
        })?;
        serde_json::from_str::<serde_json::Value>(&text).map_err(|error| WorkspaceError::Io {
            path: path.to_path_buf(),
            source: std::io::Error::new(std::io::ErrorKind::InvalidData, error),
        })?
    } else {
        serde_json::json!({})
    };
    let object = value.as_object_mut().ok_or_else(|| WorkspaceError::Io {
        path: path.to_path_buf(),
        source: std::io::Error::new(
            std::io::ErrorKind::InvalidData,
            "Claude configuration must be a JSON object",
        ),
    })?;
    let servers = object
        .entry("mcpServers")
        .or_insert_with(|| serde_json::json!({}))
        .as_object_mut()
        .ok_or_else(|| WorkspaceError::Io {
            path: path.to_path_buf(),
            source: std::io::Error::new(
                std::io::ErrorKind::InvalidData,
                "Claude mcpServers must be a JSON object",
            ),
        })?;
    servers.insert(
        "rustic-workspace".to_owned(),
        serde_json::json!({"type":"stdio","command":backend.to_string_lossy(),"args":[]}),
    );
    let bytes = serde_json::to_vec_pretty(&value).expect("Claude configuration serializes");
    files.write_with_options(path, &bytes, AtomicWriteOptions { keep_backup: true })?;
    Ok(())
}

fn update_personal_marketplace(
    path: &Path,
    files: &AtomicFileService,
) -> Result<(), WorkspaceError> {
    let mut value = if path.is_file() {
        fs::read_to_string(path)
            .ok()
            .and_then(|text| serde_json::from_str::<serde_json::Value>(&text).ok())
            .unwrap_or_else(|| serde_json::json!({}))
    } else {
        serde_json::json!({})
    };
    let object = value.as_object_mut().ok_or_else(|| WorkspaceError::Io {
        path: path.to_path_buf(),
        source: std::io::Error::new(
            std::io::ErrorKind::InvalidData,
            "personal marketplace root must be a JSON object",
        ),
    })?;
    object
        .entry("name")
        .or_insert_with(|| serde_json::json!("personal"));
    object
        .entry("interface")
        .or_insert_with(|| serde_json::json!({"displayName":"Personal"}));
    let plugins = object
        .entry("plugins")
        .or_insert_with(|| serde_json::json!([]))
        .as_array_mut()
        .ok_or_else(|| WorkspaceError::Io {
            path: path.to_path_buf(),
            source: std::io::Error::new(
                std::io::ErrorKind::InvalidData,
                "personal marketplace plugins must be an array",
            ),
        })?;
    plugins.retain(|entry| {
        entry.get("name").and_then(serde_json::Value::as_str) != Some("rustic-workspace")
    });
    plugins.push(serde_json::json!({"name":"rustic-workspace","source":{"source":"local","path":"./plugins/rustic-workspace"},"policy":{"installation":"INSTALLED_BY_DEFAULT","authentication":"ON_INSTALL"},"category":"Developer Tools"}));
    let bytes = serde_json::to_vec_pretty(&value).expect("marketplace serializes");
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|source| WorkspaceError::Io {
            path: parent.to_path_buf(),
            source,
        })?;
    }
    files.write_with_options(path, &bytes, AtomicWriteOptions { keep_backup: true })?;
    Ok(())
}

fn write_generated_or_preserve(
    files: &AtomicFileService,
    path: &Path,
    bytes: &[u8],
) -> Result<(), WorkspaceError> {
    if path.exists() {
        let old = fs::read_to_string(path).unwrap_or_default();
        if !old.contains(GENERATED_MARKER) {
            return Ok(());
        }
    }
    files.write(path, bytes)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn generation_preserves_user_settings_and_workspace() {
        let temp = tempfile::tempdir().unwrap();
        let vscode = temp.path().join(".vscode");
        fs::create_dir_all(&vscode).unwrap();
        fs::write(vscode.join("settings.json"), "{\"user\":true}").unwrap();
        fs::write(temp.path().join("Game.code-workspace"), "user owned").unwrap();
        let result = generate_programming_workspace(temp.path(), "Game").unwrap();
        assert_eq!(
            fs::read_to_string(vscode.join("settings.json")).unwrap(),
            "{\"user\":true}"
        );
        assert_eq!(
            fs::read_to_string(&result.workspace_file).unwrap(),
            "user owned"
        );
        assert!(result.generated_files.iter().all(|p| p.is_file()));
        assert!(result.agent_integration_files.iter().all(|p| p.is_file()));
        assert!(temp.path().join(".mcp.json").is_file());
        assert!(
            temp.path()
                .join(".claude/skills/rustic-workspace/SKILL.md")
                .is_file()
        );
        let cpp = fs::read_to_string(temp.path().join(".rustic/generated/programming/rustic.hpp"))
            .unwrap();
        assert!(cpp.contains("class RusticApi"));
        assert!(cpp.contains("GameApi"));
    }

    #[test]
    fn codex_mcp_install_preserves_existing_configuration() {
        let temp = tempfile::tempdir().unwrap();
        let config = temp.path().join("config.toml");
        fs::write(&config, "model = \"example\"\n").unwrap();
        update_codex_mcp(
            &config,
            Path::new("C:/Rustic/rustic-agent-backend.exe"),
            &AtomicFileService::new(),
        )
        .unwrap();
        let document = fs::read_to_string(config)
            .unwrap()
            .parse::<toml_edit::DocumentMut>()
            .unwrap();
        assert_eq!(document["model"].as_str(), Some("example"));
        assert_eq!(
            document["mcp_servers"]["rustic-workspace"]["command"].as_str(),
            Some("C:/Rustic/rustic-agent-backend.exe")
        );
        assert_eq!(
            document["mcp_servers"]["rustic-workspace"]["enabled"].as_bool(),
            Some(true)
        );
    }
}
