use engine_platform::{AtomicFileService, AtomicWriteError, AtomicWriteOptions};
use std::fs;
use std::path::{Path, PathBuf};
use thiserror::Error;

const GENERATED_MARKER: &str = "Generated by Rustic Game Engine. Safe to regenerate.";

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WorkspaceGeneration {
    pub workspace_file: PathBuf,
    pub generated_files: Vec<PathBuf>,
    pub preserved_user_files: Vec<PathBuf>,
}

#[derive(Debug, Error)]
pub enum WorkspaceError {
    #[error("workspace I/O failed at {path}: {source}")]
    Io {
        path: PathBuf,
        #[source]
        source: std::io::Error,
    },
    #[error("transactional workspace write failed: {0}")]
    Write(#[from] AtomicWriteError),
}

/// Generates reproducible VS Code metadata and EmmyLua-compatible API stubs.
/// User-owned `.vscode/settings.json` and existing non-generated files are untouched.
/// Generates reproducible metadata while preserving user-owned editor files.
///
/// # Errors
/// Returns an error when directories or transactional files cannot be created.
pub fn generate_programming_workspace(
    project_root: &Path,
    project_name: &str,
) -> Result<WorkspaceGeneration, WorkspaceError> {
    let generated = project_root.join(".rustic/generated/programming");
    fs::create_dir_all(&generated).map_err(|source| WorkspaceError::Io {
        path: generated.clone(),
        source,
    })?;
    let files = AtomicFileService::new();
    let workspace_file = project_root.join(format!("{project_name}.code-workspace"));
    let workspace = format!(
        "{{\n  \"//\": \"{GENERATED_MARKER}\",\n  \"folders\": [{{ \"path\": \".\" }}],\n  \"settings\": {{\n    \"Lua.workspace.library\": [\".rustic/generated/programming\"],\n    \"C_Cpp.default.includePath\": [\"${{workspaceFolder}}/.rustic/generated/programming\"]\n  }}\n}}\n"
    );
    write_generated_or_preserve(&files, &workspace_file, workspace.as_bytes())?;
    let extensions = generated.join("extensions.json");
    let extension_text = format!(
        "{{\n  \"//\": \"{GENERATED_MARKER}\",\n  \"recommendations\": [\"sumneko.lua\", \"dbaeumer.vscode-eslint\", \"ms-vscode.cpptools\"]\n}}\n"
    );
    files.write_with_options(
        &extensions,
        extension_text.as_bytes(),
        AtomicWriteOptions { keep_backup: false },
    )?;
    let api = generated.join("rustic_api.lua");
    let api_text = format!(
        "---@meta\n-- {GENERATED_MARKER}\n---@class RusticTransform\n---@field x number\n---@field y number\n---@field z number\n---@class RusticApi\n---@field entity_id fun(): string\n---@field delta_time fun(): number\n---@field fixed_delta_time fun(): number\n---@field get_translation fun(): number, number, number\n---@field set_translation fun(x:number,y:number,z:number)\n---@field find_entity fun(name_or_id:string): string|nil, string|nil\n---@field input fun(action:string): table\n---@field log fun(level:string,message:string,fields:table|nil)\n---@field get_property fun(name:string): any\n---@field set_property fun(name:string,value:any): boolean, string|nil\n---@field set_enabled fun(enabled:boolean)\n---@type RusticApi\nrustic = rustic\n---@class RusticInstanceApi\n---@field add fun(source:string,parent:string|nil): string\n---@field clone fun(source:string,parent:string|nil): string\n---@type RusticInstanceApi\ninstance = instance\n"
    );
    files.write_with_options(
        &api,
        api_text.as_bytes(),
        AtomicWriteOptions { keep_backup: false },
    )?;
    let javascript_api = generated.join("rustic_api.d.ts");
    let javascript_api_text = format!(
        "// {GENERATED_MARKER}\ntype RusticActionState = Readonly<{{ pressed: boolean; released: boolean; held: boolean; axis: number }}>;\ninterface RusticApi {{\n  entity_id(): string;\n  delta_time(): number;\n  fixed_delta_time(): number;\n  get_translation(): [number, number, number];\n  set_translation(x: number, y: number, z: number): void;\n  input(action: string): RusticActionState;\n  log(level: string, message: string): void;\n  get_property(name: string): unknown;\n  set_property(name: string, value: unknown): void;\n  set_enabled(enabled: boolean): void;\n}}\ndeclare const rustic: Readonly<RusticApi>;\ndeclare const instance: Readonly<{{ add(source: string, parent?: string | null): void; clone(source: string, parent?: string | null): void }}>;\ndeclare interface RusticBehavior {{\n  on_create?(): void;\n  on_start?(): void;\n  fixed_update?(delta: number): void;\n  update?(delta: number): void;\n  on_destroy?(): void;\n  on_stop?(): void;\n}}\ndeclare var behavior: RusticBehavior;\n"
    );
    files.write_with_options(
        &javascript_api,
        javascript_api_text.as_bytes(),
        AtomicWriteOptions { keep_backup: false },
    )?;
    let cpp_api = generated.join("rustic.hpp");
    files.write_with_options(
        &cpp_api,
        crate::cpp_sdk::HEADER.as_bytes(),
        AtomicWriteOptions { keep_backup: false },
    )?;
    let protocol_schema = generated.join("rustic_host_protocol.schema.json");
    let protocol_schema_text = format!(
        "{{\n  \"$schema\": \"https://json-schema.org/draft/2020-12/schema\",\n  \"title\": \"Rustic gameplay host protocol\",\n  \"description\": \"{GENERATED_MARKER}\",\n  \"type\": \"object\",\n  \"required\": [\"format_version\", \"callback\", \"entity_id\", \"translation\", \"properties\"],\n  \"properties\": {{\n    \"format_version\": {{ \"const\": 1 }},\n    \"callback\": {{ \"enum\": [\"on_create\", \"on_start\", \"fixed_update\", \"update\", \"on_destroy\", \"on_stop\"] }},\n    \"delta\": {{ \"type\": [\"number\", \"null\"] }},\n    \"entity_id\": {{ \"type\": \"string\" }},\n    \"delta_time\": {{ \"type\": \"number\" }},\n    \"fixed_delta_time\": {{ \"type\": \"number\" }},\n    \"translation\": {{ \"type\": \"array\", \"minItems\": 3, \"maxItems\": 3, \"items\": {{ \"type\": \"number\" }} }},\n    \"properties\": {{ \"type\": \"object\" }},\n    \"attributes\": {{ \"type\": \"object\" }},\n    \"scene_paths\": {{ \"type\": \"object\" }},\n    \"actions\": {{ \"type\": \"object\" }},\n    \"keys\": {{ \"type\": \"object\" }},\n    \"key_events\": {{ \"type\": \"array\" }},\n    \"any_key_pressed\": {{ \"type\": \"boolean\" }},\n    \"commands\": {{ \"description\": \"Responses may include set_translation, set_property, edit_attribute, log, set_enabled, add_instance, or clone_instance.\", \"type\": \"array\" }}\n  }}\n}}\n"
    );
    files.write_with_options(
        &protocol_schema,
        protocol_schema_text.as_bytes(),
        AtomicWriteOptions { keep_backup: false },
    )?;
    let preserved = [
        project_root.join(".vscode/settings.json"),
        project_root.join(".vscode/tasks.json"),
        project_root.join(".vscode/launch.json"),
    ]
    .into_iter()
    .filter(|p| p.exists())
    .collect();
    Ok(WorkspaceGeneration {
        workspace_file,
        generated_files: vec![extensions, api, javascript_api, cpp_api, protocol_schema],
        preserved_user_files: preserved,
    })
}

fn write_generated_or_preserve(
    files: &AtomicFileService,
    path: &Path,
    bytes: &[u8],
) -> Result<(), WorkspaceError> {
    if path.exists() {
        let old = fs::read_to_string(path).unwrap_or_default();
        if !old.contains(GENERATED_MARKER) {
            return Ok(());
        }
    }
    files.write(path, bytes)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn generation_preserves_user_settings_and_workspace() {
        let temp = tempfile::tempdir().unwrap();
        let vscode = temp.path().join(".vscode");
        fs::create_dir_all(&vscode).unwrap();
        fs::write(vscode.join("settings.json"), "{\"user\":true}").unwrap();
        fs::write(temp.path().join("Game.code-workspace"), "user owned").unwrap();
        let result = generate_programming_workspace(temp.path(), "Game").unwrap();
        assert_eq!(
            fs::read_to_string(vscode.join("settings.json")).unwrap(),
            "{\"user\":true}"
        );
        assert_eq!(
            fs::read_to_string(&result.workspace_file).unwrap(),
            "user owned"
        );
        assert!(result.generated_files.iter().all(|p| p.is_file()));
        let cpp = fs::read_to_string(temp.path().join(".rustic/generated/programming/rustic.hpp"))
            .unwrap();
        assert!(cpp.contains("class RusticApi"));
        assert!(cpp.contains("GameApi"));
    }
}
